name: pages-build

on:
  push:
    branches:
      - develop  # O il tuo branch di riferimento

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Installa Node.js SENZA usare la cache Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # non usare "cache: yarn", altrimenti gira Yarn 1.x prima di Corepack

      # 3) Abilita Corepack
      - name: Enable Corepack
        run: corepack enable

      # 4) Installa la versione specifica di Yarn
      - name: Use the correct Yarn version
        run: corepack prepare yarn@4.5.1 --activate

      # 5) Verifica di avere Yarn 4.5.1
      - name: Verify Yarn version
        run: yarn --version

      # 6) Installa le dipendenze (ora con Yarn 4)
      - name: Install dependencies
        run: yarn install --immutable

      # 7) Builda Storybook
      - name: Build Storybook
        run: yarn build:storybook

      # 8) Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/storybook
          publish_branch: gh-pages
          destination_dir: storybook

      # 7) Builda docusaurus
      - name: Build Docusaurus
        run: yarn build:docs

      # 8) Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          # destination_dir: docusaurus

