name: pages-build

on:
  push:
    branches:
      - main  # O il tuo branch di riferimento

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # non usare "cache: yarn", altrimenti gira Yarn 1.x prima di Corepack

      - name: Enable Corepack
        run: corepack enable

      - name: Use the correct Yarn version
        run: corepack prepare yarn@4.5.1 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Docusaurus
        run: yarn build:docs

      - name: Deploy Docusaurus to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-docusaurus
          publish_branch: gh-pages
          # destination_dir: docusaurus

      - name: Build Storybook
        run: yarn build:storybook

      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-storybook
          publish_branch: gh-pages
          destination_dir: storybook
          keep_files: true
